site_name: cheat-sheet-collection
nav:
  - Home: index.md
  - Django: django/django-main.md
  - Geo-Web-Services: geo-web-services/geo-web-services.md
  - City-Files:
      - CityGML: city-files/citygml_vs_gml.md
  - X-Files:
      - XPath: x-files/xpath.md
  - YAML: yaml/yaml-main.md
  - ORACLEDB:
    - "SDO_GEOMETRY (ORACLEDB)": oracledb/sdo_geometry.md
    - "OracleDB vs PostgreSQL": oracledb/oracledb-vs-postgresql-tricks.md
  - About: about.md
theme:
    name: material
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
